FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_BASE_PATH=/
ARG STUDIO_BASE_PATH=/
ARG VITE_SUB2API_BASE_URL=
ARG VITE_SUB2API_GATEWAY_BASE_URL=
ARG VITE_SUB2API_IMAGE_ROUTE=responses
ARG VITE_SUB2API_RESPONSES_MODEL=gpt-5.5
ARG VITE_SUB2API_RESPONSES_PARTIAL_IMAGES=2
ARG VITE_SUB2API_LOGIN_URL=
ARG VITE_STUDIO_HISTORY_BASE_URL=
ARG VITE_STUDIO_BACK_URL=/
ARG VITE_STUDIO_LIBRARY_AUTH_REQUIRED=false
ENV VITE_BASE_PATH=$VITE_BASE_PATH
ENV STUDIO_BASE_PATH=$STUDIO_BASE_PATH
ENV VITE_SUB2API_BASE_URL=$VITE_SUB2API_BASE_URL
ENV VITE_SUB2API_GATEWAY_BASE_URL=$VITE_SUB2API_GATEWAY_BASE_URL
ENV VITE_SUB2API_IMAGE_ROUTE=$VITE_SUB2API_IMAGE_ROUTE
ENV VITE_SUB2API_RESPONSES_MODEL=$VITE_SUB2API_RESPONSES_MODEL
ENV VITE_SUB2API_RESPONSES_PARTIAL_IMAGES=$VITE_SUB2API_RESPONSES_PARTIAL_IMAGES
ENV VITE_SUB2API_LOGIN_URL=$VITE_SUB2API_LOGIN_URL
ENV VITE_STUDIO_HISTORY_BASE_URL=$VITE_STUDIO_HISTORY_BASE_URL
ENV VITE_STUDIO_BACK_URL=$VITE_STUDIO_BACK_URL
ENV VITE_STUDIO_LIBRARY_AUTH_REQUIRED=$VITE_STUDIO_LIBRARY_AUTH_REQUIRED
RUN npm run build

FROM nginx:1.27-alpine

COPY deploy/docker-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
